experiment_name: cifar
n_repeats: 20
scenario_params_list:
 - dataset_name:
     - 'mnist'
     - 'cifar10'
   partners_count:
     - 3
   amounts_per_partner: 
     - [0.4, 0.3, 0.3]
   samples_split_option: 
     - 'random'
     - 'stratified'
   multi_partner_learning_approach:
     - 'fedavg'
     - 'seq-pure'
     - 'seq-with-final-agg'
     - 'seqavg'
   aggregation_weighting: 
     - 'uniform'
   epoch_count: 
     - 50
   minibatch_count: 
     - 10
   gradient_updates_per_pass_count:
     - 8
