experiment_name: patience_sept
n_repeats: 40
scenario_params_list:
 - dataset_name:
    'mnist':
    - 'random_initialization'
   partners_count: 
     - 10
   amounts_per_partner: 
     - [0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1]
   samples_split_option: 
     - ['advanced', [[1, 'specific'], [1, 'specific'], [1, 'specific'], [1, 'specific'], [1, 'specific'], [1, 'specific'], [1, 'specific'], [1, 'specific'], [1, 'specific'], [1, 'specific']]]
   multi_partner_learning_approach:
     - 'seq-pure'
   aggregation_weighting: 
     - 'uniform' 
   gradient_updates_per_pass_count: 
     - 8
   epoch_count: 
     - 100
   minibatch_count: 
     - 1
     - 3
     - 10
