language: python

python:
  - "3.7"     

cache: pip

# command to install dependencies
install:
  - pip install -r requirements.txt
  - travis_wait 30 mvn install

# command to run tests
script:
  - pytest -v tests.py
  - python main.py -f config_quick_debug.yml
