language: python

python:
  - "3.7"     

cache: pip

# command to install dependencies
install:
  - pip install -r requirements.txt

# command to run tests
script:
  - flake8 --max-line-length=120
  - pytest -v tests/unit_tests.py
  - travis_wait 30 pytest -v tests/end_to_end_tests.py
