experiment_name: simple_16
n_repeats: 5
scenario_params_list:
 - partners_count: 
      - 3
   amounts_per_partner: 
      - [0.4, 0.3, 0.3] 
   samples_split_option: 
     - 'random'
     - 'stratified'
   aggregation_weighting: 
     - 'data_volume' 
     - 'uniform'
   epoch_count: 
     - 38
   methods:
     - ["Shapley values", "Independent scores", "TMCS"]
   minibatch_count: 
     - 20
   gradient_updates_per_pass_count:
     - 8
 - partners_count: 
     - 2
   amounts_per_partner: 
     - [0.5, 0.5]
   samples_split_option: 
     - 'random'
     - 'stratified'
   aggregation_weighting: 
     - 'data_volume' 
     - 'uniform'
   epoch_count: 
     - 38
   methods:
     - ["Shapley values", "Independent scores", "TMCS"]
   minibatch_count: 
     - 20
   gradient_updates_per_pass_count:
     - 8
