experiment_name: debug_config
n_repeats: 1
scenario_params_list:
 - partners_count: 
    - 2
   amounts_per_partner: 
    - [0.5, 0.5]
   dataset_name:
    - 'CIFAR10'
   samples_split_option: 
    - 'random'
   multi_partner_learning_approach:
    - 'seq-pure'
   aggregation_weighting:
    - 'uniform'
   gradient_updates_per_pass_count:
    - 8
   minibatch_count:
    - 10
   epoch_count:
    - 10
