experiment_name: patience
n_repeats: 10
scenario_params_list:
<<<<<<< HEAD
 - dataset_name:
     - 'mnist'
     - 'cifar10'
   partners_count:
     - 3
=======
 - partners_count: 
     - 10
>>>>>>> add notebook
   amounts_per_partner: 
     - [0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1]
   samples_split_option: 
     - ['basic', 'stratified']
   multi_partner_learning_approach:
     - 'fedavg'
     - 'seq-pure'
     - 'seq-with-final-agg'
     - 'seqavg'
   aggregation_weighting: 
     - 'uniform' 
   gradient_updates_per_pass_count: 
     - 4
     - 8
<<<<<<< HEAD
   dataset_proportion:
     - 1
 - dataset_name:
     - 'mnist'
   partners_count:
     - 2
   amounts_per_partner: 
     - [0.5, 0.5]
   samples_split_option:
     - ['basic', 'stratified']
   multi_partner_learning_approach:
     - 'fedavg'
   aggregation_weighting: 
     - 'data_volume' 
     - 'uniform'
=======
     - 16
>>>>>>> add notebook
   epoch_count: 
     - 100
   minibatch_count: 
     - 1
     - 2
     - 5
<<<<<<< HEAD
   dataset_proportion:
     - 1
