experiment_name: ensembling
n_repeats: 2
scenario_params_list:
 - dataset_name:
     - 'mnist'
   partners_count:
     - 3
   amounts_per_partner: 
     - [0.4, 0.3, 0.3]
   samples_split_option: 
     - ['basic', 'random']
     - ['basic', 'stratified']
   multi_partner_learning_approach:
     - 'ensembling'
   aggregation_weighting:
     - 'uniform'
   epoch_count: 
     - 10
   minibatch_count: 
     - 10
   gradient_updates_per_pass_count:
     - 8
   dataset_proportion:
     - 1
