experiment_name: debug_config
n_repeats: 1
scenario_params_list:
 - partners_count: 
    - 3
   amounts_per_partner: 
    - [0.45, 0.45, 0.1]
   samples_split_option: 
    - 'stratified'
    - 'random'
   aggregation_weighting: 
    - 'local_score'
    - 'data_volume'
   corrupted_datasets: 
    - [not_corrupted, not_corrupted, corrupted]
    - [not_corrupted, not_corrupted, not_corrupted]
   is_quick_demo: 
    - True
   methods:
    - ["Independant scores"]
 - partners_count:
    - 2
   amounts_per_partner:
    - [0.7, 0.3]
   samples_split_option:
    - 'stratified'
    - 'random'
   aggregation_weighting:
    - 'uniform'
   corrupted_datasets:
    - [not_corrupted, not_corrupted]
   is_quick_demo:
    - True
   methods:
    - ["Independant scores"]