experiment_name: simple_16
n_repeats: 10
scenario_params_list:
 - nodes_counts: 3
   amounts_per_node: [0.4, 0.3, 0.3] 
   samples_split_option: 'Random'
   single_partner_test_mode: 'global'
   epoch_number:4
 - nodes_counts: 3
   amounts_per_node: [0.9, 0.05, 0.05] 
   samples_split_option: 'Random'
   single_partner_test_mode: 'global'
 - nodes_counts: 2
   amounts_per_node: [0.9, 0.1] 
   samples_split_option: 'Random'
   single_partner_test_mode: 'global'
   