{% set name = "mplc" %}
{% set version = "0.3.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://github.com/SubstraFoundation/distributed-learning-contributivity/archive/v.0.3.1.tar.gz
  # url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  # url: "https://files.pythonhosted.org/packages/65/c3/ddd8ef8858e0b9c38123f81d5be6dbb025520e9b7e473b89cc36086b0eff/mplc-0.3.1.tar.gz"
  # sha256:
  # path: ./

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python
    - setuptools==50.3.0
 
  run:
    - h5py==2.10.0
    - joblib==1.0.0
    - librosa==0.8.0
    - matplotlib==3.3.3
    - numpy==1.19.4
    - scipy==1.5.4
    - scikit-learn==0.23.2
    - pandas==1.1.5
    - seaborn==0.11.0
    - loguru==0.5.3
    - tensorflow==2.4.0
    - ruamel.yaml==0.16.12
    - pytest==6.2.0
    - pytest-cov==2.10.1
    - flake8==3.8.3

about:
  home: https://github.com/SubstraFoundation/distributed-learning-contributivity 
  license: Apache 2.0
  license_family: APACHE
  license_file: "./LICENSE"
  summary: "MPLC"
  doc_url: https://github.com/SubstraFoundation/distributed-learning-contributivity/blob/master/README.md
  dev_url: https://github.com/SubstraFoundation/distributed-learning-contributivity/blob/master/CONTRIBUTING.md
